package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/INACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, December 18, 2014 5:35:56 PM PST
*/

public interface INACTIVE
{

  /** Object adapter state that causes all requests to be discarded.
     * This state indicates that the adapter is shutting down.
     */
  public static final short value = (short)(3);
}
